title: QSYS, INC.
email: contact@quintsys.com
description: "Custom software applications development. Technical solutions to your business problems."
url: "https://quintsys.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: qbantek
github_username:  quintsys
google_analytics: "UA-36207607-1"
permalink: pretty

plugins:
  - jekyll-assets
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - yarn.lock
  - .idea/

sass:
  load_paths:
    - _sass
    - node_modules

assets:
  sources:
    - node_modules