source 'https://rubygems.org'

gem 'html-proofer', '3.18.5'
gem 'jekyll', '~> 4.2.0'
gem 'jekyll-sitemap', '~> 1.4'
gem 'sprockets', '~> 4.0', '>= 4.0.2'
gem 'uglifier', '~> 4.2'

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-assets", git: "https://github.com/envygeeks/jekyll-assets"
  gem 'jekyll-feed', '~> 0.15'
  gem 'jekyll-seo-tag', '~> 2.7'
end


