# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node
    environment:
      JEKYLL_ENV: production
      JEKYLL_PATH: jekyll
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    working_directory: ~/quintsys-web
    steps:
      - checkout

      # gems
      - restore_cache:
          keys:
            - v4-gems-{{ .Branch }}-{{ checksum "jekyll/Gemfile.lock" }}
            - v4-gems-{{ .Branch }}
            - v4-gems
      - run:
          name: 'Bundle Gem'
          command: |
            cd $JEKYLL_PATH
            echo 'export BUNDLER_VERSION=2.0.2' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: "Bundle Install"
          command: |
            cd $JEKYLL_PATH
            bundle check --path vendor/bundle || bundle install --path vendor/bundle
      - save_cache:
          key: v4-gems-{{ .Branch }}-{{ checksum "jekyll/Gemfile.lock" }}
          paths:
            - "jekyll/vendor/bundle"

      # js packages
      - restore_cache:
          keys:
          - v4-yarn-deps-{{ .Branch }}-{{ checksum "jekyll/yarn.lock" }}
          - v4-yarn-deps-{{ .Branch }}
          - v4-yarn-deps
      - run:
          name: "Yarn Install"
          command: |
            cd $JEKYLL_PATH
            yarn
      - save_cache:
          key: v4-yarn-deps-{{ .Branch }}-{{ checksum "jekyll/yarn.lock" }}
          paths:
          - "jekyll/node_modules"

      - run:
          name: "Build the Jekyll site"
          command: |
            cd $JEKYLL_PATH
            bundle exec jekyll build
      - run:
          name: "Test with HTMLproofer"
          command: |
            cd $JEKYLL_PATH
            bundle exec htmlproofer _site --check-favicon --check-html --disable-external --empty-alt-ignore
      - store_artifacts:
          path: ~/quintsys-web/jekyll/_site
          destination: quintsys-web
      - persist_to_workspace:
          root: ~/quintsys-web
          paths:
            - jekyll/_site
            - .firebaserc
            - firebase.json
  deploy:
    docker:
      - image: circleci/node:10.10
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: "Install firebase-tools"
          command: yarn add firebase-tools --dev
      - run:
          name: "Deploy to Firebase if tests pass and branch is Master"
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
