# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/ruby:2.5.1-node-browsers

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v2-dependencies-{{ checksum "Gemfile.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v2-dependencies-

    - run:
        name: Ruby dependencies
        command: bundle install --jobs=4 --retry=3

    - run:
        name: Node dependencies
        command: npm install -g firebase-tools --unsafe-perm

    - save_cache:
        paths:
        - /usr/local/bundle
        - /usr/local/lib/node_modules
        key: v2-dependencies-{{ checksum "Gemfile.lock" }}

    - run:
        name: Build
        command: bundle exec jekyll build --verbose

    - test:
        name:
        command: bundle exec htmlproofer ./_site --check-html --disable-external